Repository ruby/net-imap, pull requests merged in 2025-01, with the labels that each got.

#366 RFC9586 UIDONLY support
  lib/net/imap.rb
  lib/net/imap/fetch_data.rb
  lib/net/imap/response_data.rb
  lib/net/imap/response_parser.rb
  rakelib/rfcs.rake
  test/net/imap/fixtures/response_parser/rfc9586_uidonly_responses.yml
  test/net/imap/test_fetch_data.rb
  test/net/imap/test_imap.rb
  test/net/imap/test_imap_response_parser.rb
Labels: enhancement

#376 🐛 Fix `SequenceSet#append` when its `@string` is nil
  lib/net/imap/sequence_set.rb
  test/net/imap/test_sequence_set.rb
Labels: bug

#377 🐛 Fix SequenceSet merging in another SequenceSet
  lib/net/imap/sequence_set.rb
  test/net/imap/test_sequence_set.rb
Labels: bug

#378 🐛 Backport SequenceSet bugfixes (#376, #377) to v0.4
  lib/net/imap/sequence_set.rb
  test/net/imap/test_sequence_set.rb
Labels: bug

#381 🔧 Ensure ResponseParser config is mutable and non-global
  lib/net/imap/response_parser.rb
  test/net/imap/test_imap_response_parser.rb
Labels: enhancement

#382 🔧 ResponseParser config is mutable and non-global (backports #381)
  lib/net/imap/response_parser.rb
  test/net/imap/test_imap_response_parser.rb
Labels: enhancement

#386 ✨ Add `SequenceSet#each_ordered_number`
  lib/net/imap/sequence_set.rb
  test/net/imap/test_sequence_set.rb
Labels: enhancement

#392 ✅ Improve UIDPlusData test coverage
  test/net/imap/test_imap_response_data.rb
  test/net/imap/test_imap_response_parser.rb
  test/net/imap/test_thread_member.rb
  test/net/imap/test_uid_plus_data.rb
Labels: tests-only
